spring:
  datasource:
    username: basketball_tourney
    password: basketball_tourney
    url: jdbc:mysql://localhost:3306/basketball_tourney


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
   